### ISSUE TITLE
inconsistent licenses

### ISSUE THREAD

**Issue by robertoostenveld** [mindaffect/pymindaffectBCI#1]
The copyright statement in some (but not all) of the py files states

```
# Copyright (c) MindAffect B.V. 2018
# For internal use only.  Distribution prohibited.
```

which is inconsistent with the MIT-like license that you apply to the whole repository. I propose you make them consistent, and that you add a consistent copyright statement to each of the files that you are distributing.

**Comment by jadref** [comment]
Thanks for the report, we will all the copyright statements to be consistent with the MIT license.
