### ISSUE TITLE
cannot find python executable

### ISSUE THREAD

**Issue by robertoostenveld** [mindaffect/pymindaffectBCI#3]
https://github.com/mindaffect/pymindaffectBCI/blob/2eb4d83cb6049992cfeb6b1bd82dd62c2190fbb6/mkpkg.sh#L1

Executable Python scripts should also work with Anaconda and other installers, which result in the python interpreter being elsewhere.

You should start the script with 
```
#!/usr/bin/env python3
```
to make it independent from the specific python location, but to use the one that the user has on his/her path. 

This might  of course also apply to other `.py` files.

**Comment by jadref** [comment]
Thanks, I believe now resolved.
