### ISSUE TITLE
Cannot make it work correclty the brain signals

### ISSUE THREAD

**Issue by Darkhan92** [mindaffect/pymindaffectBCI#44]
Hello dear Mindaffect community. I have installed and made it run. But the problem is, it does not show a good reaction to the brain signals, it shows only the noise without reaction even to the eye blink. It is installed on windows 10. I did the recommendation that going to device manager and changed some properties like acquisition receives bytes and latency. But still, it does not help me. For the filtering, I did not change any properties. I am using OPEN BCI Cyton, so I changed like com7 and id=0. So it reads the signal and it reacts only when I move the board itself. But when I wear a headband, in general shows only noise. What can be a solution?
![image](https://user-images.githubusercontent.com/49669134/142974936-ee2b7d19-3b59-4e21-86b1-a31050e66130.png)

**Comment by Darkhan92** [comment]
![image](https://user-images.githubusercontent.com/49669134/142975007-922437f0-b430-4fa7-bfca-a23bedb02e0f.png)
This is how it looks when I move the board. So it means it reads the board signal correctly, but the accusation itself does not show a real signal from the brain.

**Comment by jadref** [comment]
Dear Darkhan92,

Sorry to hear you are having such signal quality issues.  In general this is an indication of one or both of:
1) a poor connection between the amplifier and the scalp of your subject
2) a lot of nearby electrical interference sources

To address the first problem you need to ensure that the connection between the amp and the body is good.   There is a lot of material on this online, see e.g. the openBCI getting started guide: <https://github.com/openbci-archive/Docs/blob/master/Tutorials/01-Cyton_Getting%20Started_Guide.md>.  It's important that you have a good skin connection (sufficient water for water electrodes, clean skin and enough gel for gel electrodes).  Also it's very important that you have wired up the electrodes correctly.  Specifically, ensure ensure you have the BIAS and SRT electrodes connected to the body correctly -- these electrodes are a key part of the cyton's noise cancelling system so poor connection here has a significant impact.

To address the 2nd problem there are a number of steps you can take:
1) ensure the cables are solidly connected -- loose connections tend to pick up a lot of external noise.
2) ensure the cables are not prone to movement.  You can also 'braid' or 'twist' the cables round each other to reduce sensitivity to external noise.
3) ensure the amplifier and cable run to the head are as far away from external interference sources as possible.  Note: it it not always easy to see where electrical interference is coming from -- as wires may be hidden in walls.  In the end trying outside far from buildings, or in the center of a room can help a lot.

I hope you can resolve your signal to noise issues! and wish you good luck using our BCI.

Jason

**Comment by Darkhan92** [comment]
Thank you, professor Jason!

With your helpful comments, I solved my issues. Now it works well. For me helped I think correct placement headband. Grounding cables to the board and to the ear.

**Comment by jadref** [comment]
Dear Darkhan92,  great to hear, and glad to be of help.  I wish you good luck with your BCI adventures!

**Comment by iampalop** [comment]
Hello @Darkhan92,
I have the same problem as you and I have the BIAS and SRT electrodes connected, but the signal is still bad.
Which electrode did you use? dry electrode or wet electrode?

**Comment by Darkhan92** [comment]
> Hello @Darkhan92,
> I have the same problem as you and I have the BIAS and SRT electrodes connected, but the signal is still bad.
> Which electrode did you use? dry electrode or wet electrode?
> 

I have used dry electrodes from OPEN BCI. Sorry for late reply
